# Generated by Django 4.1.3 on 2022-11-03 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('isDiscoverable', models.BooleanField(default=True)),
                ('profilePicture', models.ImageField(upload_to='Profile-Pictures')),
                ('position', models.CharField(max_length=100)),
                ('biography', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
