# Generated by Django 4.1.3 on 2022-11-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usercertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificate',
            name='issueDate',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='issuedBy',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='link',
            field=models.CharField(max_length=150),
        ),
    ]
